---
name: Moodle Docker Image Upload

env:
  project_name: moodle

on:
  push:
    paths:
      - 'moodle/**'
jobs:
  push-image:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        working-directory: ./${{project_name}}
        run: DOCKER_BUILDKIT=1 make build
      - name: Push
        working-directory: ./${{project_name}}
        run: make push
  update-readme:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
      - name: Sync ReadMe with Docker Hub
        uses: ms-jpq/sync-dockerhub-readme@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/${{env.project_name}}
          readme: "./${{env.project_name}}/README.md"
